### ISSUE TITLE
npm/github install

### ISSUE THREAD

**Issue by Baransu** [csbun/gitbook-plugin-chart#5]
I was trying to use this plugin by adding it to `book.json` but with that it's not working.
After that I forked the repo and added forked version to `book.json`. Right now it works even without any change. Is npm version the same as version in github repo?

**Comment by Baransu** [comment]
It seems like not problem with npm/github but with assets path. In repo this is `./assets` and after building page with that I have no chart. But after changing it to `./assets/` it works. This may be solution.

**Comment by csbun** [comment]
I publish a new version 0.2.0 on npm, reinstall it and have fun! 😝

**Comment by csbun** [comment]
Please let me know if it fixed your problem so i can close this issue.

**Comment by Baransu** [comment]
Thank you a lot. It works like a charm :)
