### ISSUE TITLE
C3 Tick text formatting

### ISSUE THREAD

**Issue by grollinger** [csbun/gitbook-plugin-chart#6]
Hi, I'm trying to get an [example from the C3 site](https://c3js.org/samples/axes_y_tick_format.html) to work in gitbook.

The basic things work fine, but as soon as I try to specify a custom format for the axis ticks, the whole chart disappears.

Do you know of a way to make it work in gitbook?

```gitbook
{% chart format="json" %}
{
"data": {
        "columns": [
            ["a", 0.97, 0.70],
            ["b", 0.80, 0.635]
        ],
        "type": "bar"
    },
    "axis" : {
      "x" : {
          "type" : "category",
          "categories": ["cat1", "cat2"]
      },
      "y": {
          "tick" : {
             // None of these work
              "format": "d3.format('.0%')"
              "format": d3.format(".0%")
              "format": "function(d) {return d+'%';}"
              "format": function(d) {return d+"%";}
          }
      }
    },
    "bar": {
        "width": {
            "ratio": 0.1 
        }
    }
}
{% endchart %}
```

**Comment by csbun** [comment]
The former version ONLY support JSON in chart block. So `d3.format()` function can not be recognized. I upgrade a new version `0.2.1` to support this feature, pls try~
